--| Help for R15 model Zombie |--
--
-- To edit the zombie's damage go to LeftLowerArm/RightLowerArm > Damage Script > human.Health = human.Health - 5
--                                                                                              Edit the number to whatever you'd like
-- The player will recieve damage from the LeftLowerArm and RightLowerArm
-- To edit the walkspeed go to Humanoid > Scroll to the bottom > Edit the number shown after WalkSpeed
-- You can also edit max health and spawn health under Humanoid > game
--
-- Have fun!
--
-- ImFarAway